pipeline {
    agent none
    stages {
        stage ("Front-end"){
            agent{
                docker { image 'node:16-alpine'}
            }
            steps{
                sh 'node --version'
            }
        }
    }
}
