pipeline{
    agent any
    parameters{
        booleanParam(defaultValue: false, description: 'Enable Servce', name: 'myBoolean')
    }
    stages{
        stage("Boolean Demo"){
            steps{
                echo "booleanParam is set to: ${params.myBoolean}"
            }
        }
    }
}