pipeline{
    agent any
    parameters{
        string(defaultValue: "TEST", description: 'Which Env', name: 'envType')
    }
    stages{
        stage("String Demo"){
            steps{
                echo "Environment to deploy: ${params.envType}"
            }
        }
    }
}