pipeline {
    agent {
        docker {
            image 'node:17-alpine'
        }
    }
    stages {
        stage {
            steps {
                sh 'node --version'
            }
        }
    }
}