pipeline {
    agent any
    stages{
        stage("Multiple Shell"){
            steps{
                sh """
                    echo "Hello World"
                    echo "This is a multiple line shell script"
                    echo "This is the last line"
                """
            }
        }
    }
}